info:
  contact: {}
paths:
  /index:
    get:
      consumes:
      - application/json
      description: index api page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - index
swagger: "2.0"
